notes:
    path:     /notes
    defaults: { _controller: NoteBundle:Note:index }
    methods: [GET]
    requirements:
        _format: json

get_note:
    path:     /notes/{id}
    defaults: { _controller: NoteBundle:Note:get }
    methods: [GET]
    requirements:
        _format: json

save_note:
    path:     /notes
    defaults: { _controller: NoteBundle:Note:save }
    methods: [POST]
    requirements:
        _format: json

update_note:
    path:     /notes/{id}
    defaults: { _controller: NoteBundle:Note:update }
    methods: [PUT]
    requirements:
        _format: json

partial_update:
    path:     /notes/{id}
    defaults: { _controller: NoteBundle:Note:partialUpdate }
    methods: [PATCH]
    requirements:
        _format: json

remove_all_notes:
    path:     /notes
    defaults: { _controller: NoteBundle:Note:removeAll }
    methods: [DELETE]
    requirements:
        _format: json

types:
    path:     /types
    defaults: { _controller: NoteBundle:NoteType:index }
    methods: [GET]
    requirements:
        _format: json

