NoteBundle\Entity\Note:
    getters:
        validFormat:
            - 'IsTrue':
                message: Invalid format.
        title:
            - NotBlank:
        note:
            - NotBlank:
        status:
            - Choice: [regular, deleted, removed]