<?php

namespace NoteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoteTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteTypeRepository extends EntityRepository
{
}
